//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        BlogApp.ServiceReference1.HelloWorldResponse HelloWorld(BlogApp.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogApp.ServiceReference1.HelloWorldResponse> HelloWorldAsync(BlogApp.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBlog", ReplyAction="*")]
        BlogApp.ServiceReference1.CreateBlogResponse CreateBlog(BlogApp.ServiceReference1.CreateBlogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBlog", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogApp.ServiceReference1.CreateBlogResponse> CreateBlogAsync(BlogApp.ServiceReference1.CreateBlogRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public BlogApp.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(BlogApp.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogApp.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(BlogApp.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBlogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBlog", Namespace="http://tempuri.org/", Order=0)]
        public BlogApp.ServiceReference1.CreateBlogRequestBody Body;
        
        public CreateBlogRequest() {
        }
        
        public CreateBlogRequest(BlogApp.ServiceReference1.CreateBlogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBlogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        public CreateBlogRequestBody() {
        }
        
        public CreateBlogRequestBody(string title, string content) {
            this.title = title;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBlogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBlogResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogApp.ServiceReference1.CreateBlogResponseBody Body;
        
        public CreateBlogResponse() {
        }
        
        public CreateBlogResponse(BlogApp.ServiceReference1.CreateBlogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBlogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateBlogResult;
        
        public CreateBlogResponseBody() {
        }
        
        public CreateBlogResponseBody(string CreateBlogResult) {
            this.CreateBlogResult = CreateBlogResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : BlogApp.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<BlogApp.ServiceReference1.WebService1Soap>, BlogApp.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogApp.ServiceReference1.HelloWorldResponse BlogApp.ServiceReference1.WebService1Soap.HelloWorld(BlogApp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            BlogApp.ServiceReference1.HelloWorldRequest inValue = new BlogApp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new BlogApp.ServiceReference1.HelloWorldRequestBody();
            BlogApp.ServiceReference1.HelloWorldResponse retVal = ((BlogApp.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogApp.ServiceReference1.HelloWorldResponse> BlogApp.ServiceReference1.WebService1Soap.HelloWorldAsync(BlogApp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogApp.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            BlogApp.ServiceReference1.HelloWorldRequest inValue = new BlogApp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new BlogApp.ServiceReference1.HelloWorldRequestBody();
            return ((BlogApp.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogApp.ServiceReference1.CreateBlogResponse BlogApp.ServiceReference1.WebService1Soap.CreateBlog(BlogApp.ServiceReference1.CreateBlogRequest request) {
            return base.Channel.CreateBlog(request);
        }
        
        public string CreateBlog(string title, string content) {
            BlogApp.ServiceReference1.CreateBlogRequest inValue = new BlogApp.ServiceReference1.CreateBlogRequest();
            inValue.Body = new BlogApp.ServiceReference1.CreateBlogRequestBody();
            inValue.Body.title = title;
            inValue.Body.content = content;
            BlogApp.ServiceReference1.CreateBlogResponse retVal = ((BlogApp.ServiceReference1.WebService1Soap)(this)).CreateBlog(inValue);
            return retVal.Body.CreateBlogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogApp.ServiceReference1.CreateBlogResponse> BlogApp.ServiceReference1.WebService1Soap.CreateBlogAsync(BlogApp.ServiceReference1.CreateBlogRequest request) {
            return base.Channel.CreateBlogAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogApp.ServiceReference1.CreateBlogResponse> CreateBlogAsync(string title, string content) {
            BlogApp.ServiceReference1.CreateBlogRequest inValue = new BlogApp.ServiceReference1.CreateBlogRequest();
            inValue.Body = new BlogApp.ServiceReference1.CreateBlogRequestBody();
            inValue.Body.title = title;
            inValue.Body.content = content;
            return ((BlogApp.ServiceReference1.WebService1Soap)(this)).CreateBlogAsync(inValue);
        }
    }
}
